<?php

    include_once 'apiRoles.php';

    $api = new ApiRoles();
    $datosRecibidos = file_get_contents("php://input");
    $datos = json_decode($datosRecibidos);
    $item = array(
        'descripcionRol' => $datos->descripcionRol,
        'accedeRrhh' => $datos->accedeRrhh,
        'fichaEmpleado' => $datos->fichaEmpleado,
        'solicitudContratacion' => $datos->solicitudContratacion,
        'preAprobacionDeSolicitud' => $datos->preAprobacionDeSolicitud,
        'aprobacionDeSolicitud' => $datos->aprobacionDeSolicitud,
        'fichaDeContrato' => $datos->fichaDeContrato,
        'cargoOrganizacional' => $datos->cargoOrganizacional,
        'mantenedorAreaDeNegocio' => $datos->mantenedorAreaDeNegocio,
        'datosLaboralesPorVencer' => $datos->datosLaboralesPorVencer,
        'solicitudContrPendiente' => $datos->solicitudContrPendiente,
        'solicitudContratacion2' => $datos->solicitudContratacion2,
        'nacionalidad' => $datos->nacionalidad,
        'comuna' => $datos->comuna,
        'afp' => $datos->afp,
        'salud' => $datos->salud,
        'turnosLaborales' => $datos->turnosLaborales,
        'empresas' => $datos->empresas,
        'documento' => $datos->documento,
        'tipoEpp' => $datos->tipoEpp,
        'antecedentesMedicos' => $datos->antecedentesMedicos,
        'cargos' => $datos->cargos,
        'tipoEquipo' => $datos->tipoEquipo,
        'tipoAnexo' => $datos->tipoAnexo,
        'tipoEstudio' => $datos->tipoEstudio,
        'tipoTerminoDeContrato' => $datos->tipoTerminoDeContrato,
        'contactoParentesco' => $datos->contactoParentesco,
        'requisitosDeSeleccion' => $datos->requisitosDeSeleccion,
        
        // Campos de Máquinas (Activos)
        'accedeActivos' => $datos->accedeActivos,
        'informeDocumentoMaquina' => $datos->informeDocumentoMaquina,
        'deMaquina' => $datos->deMaquina,
        'claseMaquina' => $datos->claseMaquina,
        'tipoBus' => $datos->tipoBus,
        'tipoMaquina' => $datos->tipoMaquina,
        'tipoDocumentoMaquina' => $datos->tipoDocumentoMaquina,
        'tipoEquipamientoMaquina' => $datos->tipoEquipamientoMaquina,
        'tipoPolizaSeguro' => $datos->tipoPolizaSeguro,
        'marcaChasis' => $datos->marcaChasis,
        'modeloChasis' => $datos->modeloChasis,
        'marcaCarroceria' => $datos->marcaCarroceria,
        'modeloCarroceria' => $datos->modeloCarroceria,
        'proveedores' => $datos->proveedores,
        'aseguradora' => $datos->aseguradora,
        
        // Campos de Contabilidad
        'accedeContabilidad' => $datos->accedeContabilidad,
        'misRendiciones' => $datos->misRendiciones,
        'gestionarRendiciones' => $datos->gestionarRendiciones,
        'asignacionFdoRendicion' => $datos->asignacionFdoRendicion,
        'preAprobacionFdoRendicion' => $datos->preAprobacionFdoRendicion,
        'aprobacionFdoRendicion' => $datos->aprobacionFdoRendicion,
        'maestroProveedor' => $datos->maestroProveedor,
        'condicionPago' => $datos->condicionPago,
        'tipoProveedor' => $datos->tipoProveedor,
        'comunaContabilidad' => $datos->comunaContabilidad,
        'criticidad' => $datos->criticidad,
        'clientes' => $datos->clientes,
        
        // Campos de Bodega
        'accedeBodegas' => $datos->accedeBodegas,
        'entregaRepuestoOt' => $datos->entregaRepuestoOt,
        'entregaProducto' => $datos->entregaProducto,
        'generarTraspasoBodega' => $datos->generarTraspasoBodega,
        'solicitarAnulacionEntregaSms' => $datos->solicitarAnulacionEntregaSms,
        'aprobarSolicitudAnulacionEntregaSms' => $datos->aprobarSolicitudAnulacionEntregaSms,
        'recepcionOrdenCompra' => $datos->recepcionOrdenCompra,
        'recepcionTraspaso' => $datos->recepcionTraspaso,
        'informeInventario' => $datos->informeInventario,
        'kardexProducto' => $datos->kardexProducto,
        'ajusteInventario' => $datos->ajusteInventario,
        'stockBodegaProducto' => $datos->stockBodegaProducto,
        'quiebreStock' => $datos->quiebreStock,
        'listaSmsPendiente' => $datos->listaSmsPendiente,
        'listaRecepcionOc' => $datos->listaRecepcionOc,
        'listaEntregaSms' => $datos->listaEntregaSms,
        'consultaAjusteInventario' => $datos->consultaAjusteInventario,
        'informeEntregaSms' => $datos->informeEntregaSms,
        'evaluacionProveedor' => $datos->evaluacionProveedor,
        'maestroProducto' => $datos->maestroProducto,
        'maestroRepuesto' => $datos->maestroRepuesto,
        'familiaRepuesto' => $datos->familiaRepuesto,
        'subfamiliaRepuesto' => $datos->subfamiliaRepuesto,
        'deMarca' => $datos->deMarca,
        'deModelo' => $datos->deModelo,
        'sistemaAplicacion' => $datos->sistemaAplicacion,
        'unidadMedida' => $datos->unidadMedida,
        'motivoAjusteInventario' => $datos->motivoAjusteInventario,
        'tipoDocumentoAjusteInventario' => $datos->tipoDocumentoAjusteInventario,
        'categoria' => $datos->categoria,
        'subCategoria' => $datos->subCategoria,
        'deBodega' => $datos->deBodega,
        
        // Campos de Compras
        'accedeCompras' => $datos->accedeCompras,
        'generarOc' => $datos->generarOc,
        'aprobarOc' => $datos->aprobarOc,
        'generaSms' => $datos->generaSms,
        'preAprobarSms' => $datos->preAprobarSms,
        'aprobarSms' => $datos->aprobarSms,
        'anularSms' => $datos->anularSms,
        'consultaOrdenCompra' => $datos->consultaOrdenCompra,
        'ocPendienteRecepcion' => $datos->ocPendienteRecepcion,
        'consultaListaOc' => $datos->consultaListaOc,
        'consultaListaDetalleOc' => $datos->consultaListaDetalleOc,
        'consultaSolicitudMaterialServicio' => $datos->consultaSolicitudMaterialServicio,
        'consultaListaSms' => $datos->consultaListaSms,
        'consultaListaDetalleSms' => $datos->consultaListaDetalleSms,
        'historialOcProveedor' => $datos->historialOcProveedor,
        'historialOcRepuesto' => $datos->historialOcRepuesto,
        'plazoOrdenCompra' => $datos->plazoOrdenCompra,
        'formaPagoOrdenCompra' => $datos->formaPagoOrdenCompra,
        'plazoEntregaOrdenCompra' => $datos->plazoEntregaOrdenCompra,
        'tipoSolicitudMaterialServicio' => $datos->tipoSolicitudMaterialServicio,
        'tipoDocumentoProveedor' => $datos->tipoDocumentoProveedor,
        'tipoDocumentoCajaChica' => $datos->tipoDocumentoCajaChica,
        
        // Campos de Mantención
        'accedeMantencion' => $datos->accedeMantencion,
        'reporteFalla' => $datos->reporteFalla,
        'preventivaOt' => $datos->preventivaOt,
        'otInterna' => $datos->otInterna,
        'servicioExternoOt' => $datos->servicioExternoOt,
        'asignarTareasPendientes' => $datos->asignarTareasPendientes,
        'editarOt' => $datos->editarOt,
        'terminarTareaOt' => $datos->terminarTareaOt,
        'registroKm' => $datos->registroKm,
        'editarKmMaquina' => $datos->editarKmMaquina,
        'ordenTrabajo' => $datos->ordenTrabajo,
        'repuestos' => $datos->repuestos,
        'listaOts' => $datos->listaOts,
        'tareasAsignadas' => $datos->tareasAsignadas,
        'campana' => $datos->campana,
        'pautaMantencion' => $datos->pautaMantencion,
        'sistemaMaquina' => $datos->sistemaMaquina,
        'subsistemaMaquina' => $datos->subsistemaMaquina,
        'tipoTareaMantencion' => $datos->tipoTareaMantencion,
        'nivelCriticidad' => $datos->nivelCriticidad,
        'secuenciaPauta' => $datos->secuenciaPauta,
        'detencionProgramada' => $datos->detencionProgramada,
        'modificacionDetencion' => $datos->modificacionDetencion,
        'categoriaPautaInspeccion' => $datos->categoriaPautaInspeccion,
        'conductores' => $datos->conductores,
        
        // Campos de Configuración
        'accedeConfiguracion' => $datos->accedeConfiguracion,
        'roles' => $datos->roles,
        'usuarios' => $datos->usuarios,
        'configuracionGeneral' => $datos->configuracionGeneral,
        'logsSistema' => $datos->logsSistema,
        'backupRestauracion' => $datos->backupRestauracion
    );
    $api -> agregarApi($item);
?>